### ISSUE TITLE
Arbitrary group definitions with new toml file format.

### ISSUE THREAD

**Issue by proofit404** [pypa/pipfile#48]
If I understand correctly previous version of Pipfile was build around python like syntax and allows define arbitrary groups like that:

```python
package('django')

with group('develop'):
    package('django-debug-toolbar')

with group('test'):
    package('pytest')

with group('develop', 'test'):
    package('django-extensions')
```
And I could define any group I want and install it explicitly, correct?

How can I define similar pipfile with recent toml syntax?

**Comment by pradyunsg** [comment]
To quote from the README:

> Custom groups may be added in the future. Remember, it is easier to add features in the future than it is to remove them. The Composer community has been successful with only default and development as group options for many years — I'd like to follow this model, at first.

So, currently, let's experiment with just 2 groups. If the need arises, the ability to specify custom groups would be added.

---

IF they are added, I imagine the syntax would some improved form of:

```toml
[packages.default]
django = "*"

[packages.develop]
django-extensions = "*"

[packages.test]
_inherits = "develop"  # I imagine there would be inheritance
pytest = "*"
```
