### ISSUE TITLE
How to specify a second pypi-type repository

### ISSUE THREAD

**Issue by rkhwaja** [pypa/pipfile#77]
I have
`[[source]]
url = "https://pypi.python.org/simple"`

How do I specify a second source for a private repository?

**Comment by kennethreitz** [comment]
Excellent question!

**Comment by pradyunsg** [comment]
Like so:

```toml
[[source]]
url = "https://pypi.python.org/simple"

[[source]]
url = "https://pypi.my-company-page.com/simple"
```

See: https://github.com/toml-lang/toml#array-of-tables
