### ISSUE TITLE
Import / include settings from other files by reference

### ISSUE THREAD

**Issue by brianmhunt** [pypa/pipfile#85]
Putting common settings into a separate file and including them by reference can simplify config files, aid in clarity, and improve reusability.

A potential format might be e.g.

```toml
# Include everything
[[include]]
source = "../UseEverything"

# Include only specific parts
[[include]]
source = "../OnlyRequires"
parts = ['requires']

# Link from the Internet
[[include]]
source = "https://example.com/someInternetSettings"
sha256 = "edeaaff3f1774ad2888673770c6d64097e391bc362d7d6fb34982ddf0efd18cb"
```
