### ISSUE TITLE
[request] in addition to [packages] and [dev-packages] could we support [test-packages] etc.

### ISSUE THREAD

**Issue by egustavson** [pypa/pipfile#99]
I see the following as separate use cases that require different sets of dependencies:
 - packages (least inclusive)
 - test-packages 
 - dev-packages (most inclusive)

The reason this would be nice is so that my dev-packages could have things like jupyter notebooks in them which are useful for development but too heavy for testing. Having a test-packages level would let me do tests on jenkins for CI/CD using pipenv cleanly.

Alternative might be to allow you to define any prefix (dev-, test-) and pass that in somehow. 

Not sure if this request fits in with your approach, but thought I would throw it out there. Been using pipenv and it's been working great, Thanks!

**Comment by bbarker** [comment]
+1 for allowing the definition of any prefix

**Comment by stsewd** [comment]
This also is the case of rtd, where there are several requirements files https://github.com/rtfd/readthedocs.org/tree/master/requirements

**Comment by adevore** [comment]
TOML's nesting tables may be a better fit.

```toml
[env-packages.dev]
sqlite3 = "*"

[env-packages.test]
psycopg2 = "*"
```

Unfortunately, the table style of package specifications clashes with using `[packages.<env>]`. So unless a prefix besides `packages` is used, this:

```toml
[packages.test]
psycopg2 = "*"
```

is equivalent to this:

```toml
[packages]
test = { psycopg2 = "*" }
```
